### ISSUE TITLE
Won't launch on MacOS

### ISSUE THREAD

**Issue by popdynamite5511** [KingYeezus/Ye-Loves-You-b1.7.3#2]
Game will not launch on MacOS, it just shows a black screen.

**Comment by Gav06** [comment]
use windows or linux then :^)

**Comment by master7720** [comment]
facts

**Comment by popdynamite5511** [comment]
not helpful

**Comment by master7720** [comment]
> not helpful

dont waste yo money kid spend stuff on a good pc

**Comment by master7720** [comment]
@popdynamite5511 use this https://manjaro.org/download/

**Comment by master7720** [comment]
best OS

**Comment by popdynamite5511** [comment]
> > not helpful
> 
> dont waste yo money kid spend stuff on a good pc

... my macbook is 12 years old i definitly haven't wasted my money if it has lasted this long

**Comment by K1llb0t** [comment]
> @popdynamite5511 use this https://manjaro.org/download/

based, but if hes switching i would recommend PopOS!

i use debian btw

**Comment by popdynamite5511** [comment]
i'm not switching

**Comment by master7720** [comment]
i use arch btw

**Comment by master7720** [comment]
and ubuntu btw

**Comment by master7720** [comment]
> i'm not switching

https://www.youtube.com/watch?v=0BOo42F-kLw

**Comment by popdynamite5511** [comment]
> > i'm not switching
> 
> https://www.youtube.com/watch?v=0BOo42F-kLw

nah

**Comment by K1llb0t** [comment]
> i use arch btw

cool

**Comment by master7720** [comment]
> > @popdynamite5511 use this https://manjaro.org/download/
> 
> based, but if hes switching i would recommend PopOS!
> 
> i use debian btw

based.

**Comment by KingYeezus** [comment]
compile urself for java 8 compatibility

**Comment by OrangeMan432** [comment]
It seems to not work on linux either, Im on Debian with Java 17 and when I join 2beta2t, the screen goes white, then black.
```
MultiMC version: 0.7.0-3860


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.40, 2620:1ec:bdf::40]

textures.minecraft.net resolves to:
    [13.107.246.40, 2620:1ec:bdf::40]

api.mojang.com resolves to:
    [13.107.246.40, 2620:1ec:bdf::40]


Minecraft folder is:
/home/user/.local/share/multimc/instances/b1.7.3/.minecraft


Java path is:
/usr/bin/java


Checking Java version...
Java is version 17.0.11, using 64-bit architecture, from Debian.


Intel(R) Celeron(R) N4500 @ 1.10GHz
Intel Corporation JasperLake [UHD Graphics] (rev 01)

DeviceName: VGA compatible controller

Subsystem: Intel Corporation JasperLake [UHD Graphics]

Main Class:
  

Native path:
  /home/user/.local/share/multimc/instances/b1.7.3/natives

Traits:
traits legacyLaunch
traits texturepacks

Libraries:
  /home/user/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/user/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/user/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/user/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/user/.local/share/multimc/libraries/com/mojang/minecraft/b1.7.3/minecraft-b1.7.3-client.jar

Native libraries:
  /home/user/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/user/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar

Params:
  

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 54957


Using onesix launcher.

Launching with applet wrapper...
16 achievements
151 recipes
Setting user: OrangeMan432, token:<ACCESS TOKEN>:<PROFILE ID>
Jul 15, 2024 5:41:55 AM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.LinuxEnvironmentPlugin
Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event0): Failed to open device /dev/input/event0 (13)


Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event1): Failed to open device /dev/input/event1 (13)


Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event10): Failed to open device /dev/input/event10 (13)


Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event2): Failed to open device /dev/input/event2 (13)


Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event3): Failed to open device /dev/input/event3 (13)


Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event4): Failed to open device /dev/input/event4 (13)


Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event5): Failed to open device /dev/input/event5 (13)


Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event6): Failed to open device /dev/input/event6 (13)


Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
INFO: Failed to open device (/dev/input/event7): Failed to open device /dev/input/event7 (13)


Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
INFO: Linux plugin claims to have found 0 controllers


Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

Failed to add READ_ME_I_AM_VERY_IMPORTANT
Failed to add pack.mcmeta
java.io.FileNotFoundException: http://s3.amazonaws.com/MinecraftResources/
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2018)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1611)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at cz.run(SourceFile:28)
Connecting to 2beta2t.net, 25565
Stopping!

SoundSystem shutting down...
    Author: Paul Lamb, www.paulscode.com

Exception in thread "Minecraft main thread" org.lwjgl.LWJGLException: X Error - disp: 0x7931d8043840 serial: 8434 error: GLXBadWindow request_code: 152 minor_code: 32
	at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
	at org.lwjgl.opengl.LinuxDisplay.nDestroyWindow(Native Method)
	at org.lwjgl.opengl.LinuxDisplay.destroyWindow(LinuxDisplay.java:592)
	at org.lwjgl.opengl.Display.destroyWindow(Display.java:351)
	at org.lwjgl.opengl.Display.access$400(Display.java:65)
	at org.lwjgl.opengl.Display$5.destroy(Display.java:835)
	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
	at net.minecraft.client.Minecraft.d(SourceFile:588)
	at net.minecraft.client.Minecraft.run(SourceFile:848)
	at java.base/java.lang.Thread.run(Thread.java:840)
Process exited with exit code 0 (0x0).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 15 Jul 2024 05:43:44 +0000

```

**Comment by master7720** [comment]
> It seems to not work on linux either, Im on Debian with Java 17 and when I join 2beta2t, the screen goes white, then black.
> 
> ```
> MultiMC version: 0.7.0-3860
> 
> 
> Launched instance in online mode
> 
> authserver.mojang.com resolves to:
>     [N/A]
> 
> session.minecraft.net resolves to:
>     [13.107.246.40, 2620:1ec:bdf::40]
> 
> textures.minecraft.net resolves to:
>     [13.107.246.40, 2620:1ec:bdf::40]
> 
> api.mojang.com resolves to:
>     [13.107.246.40, 2620:1ec:bdf::40]
> 
> 
> Minecraft folder is:
> /home/user/.local/share/multimc/instances/b1.7.3/.minecraft
> 
> 
> Java path is:
> /usr/bin/java
> 
> 
> Checking Java version...
> Java is version 17.0.11, using 64-bit architecture, from Debian.
> 
> 
> Intel(R) Celeron(R) N4500 @ 1.10GHz
> Intel Corporation JasperLake [UHD Graphics] (rev 01)
> 
> DeviceName: VGA compatible controller
> 
> Subsystem: Intel Corporation JasperLake [UHD Graphics]
> 
> Main Class:
>   
> 
> Native path:
>   /home/user/.local/share/multimc/instances/b1.7.3/natives
> 
> Traits:
> traits legacyLaunch
> traits texturepacks
> 
> Libraries:
>   /home/user/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
>   /home/user/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
>   /home/user/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
>   /home/user/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
>   /home/user/.local/share/multimc/libraries/com/mojang/minecraft/b1.7.3/minecraft-b1.7.3-client.jar
> 
> Native libraries:
>   /home/user/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
>   /home/user/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar
> 
> Params:
>   
> 
> Window size: 854 x 480
> 
> Java Arguments:
> [-Xms512m, -Xmx1024m, -Duser.language=en]
> 
> 
> Minecraft process ID: 54957
> 
> 
> Using onesix launcher.
> 
> Launching with applet wrapper...
> 16 achievements
> 151 recipes
> Setting user: OrangeMan432, token:<ACCESS TOKEN>:<PROFILE ID>
> Jul 15, 2024 5:41:55 AM net.java.games.input.DefaultControllerEnvironment getControllers
> INFO: Loading: net.java.games.input.LinuxEnvironmentPlugin
> Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
> INFO: Failed to open device (/dev/input/event0): Failed to open device /dev/input/event0 (13)
> 
> 
> Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
> INFO: Failed to open device (/dev/input/event1): Failed to open device /dev/input/event1 (13)
> 
> 
> Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
> INFO: Failed to open device (/dev/input/event10): Failed to open device /dev/input/event10 (13)
> 
> 
> Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
> INFO: Failed to open device (/dev/input/event2): Failed to open device /dev/input/event2 (13)
> 
> 
> Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
> INFO: Failed to open device (/dev/input/event3): Failed to open device /dev/input/event3 (13)
> 
> 
> Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
> INFO: Failed to open device (/dev/input/event4): Failed to open device /dev/input/event4 (13)
> 
> 
> Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
> INFO: Failed to open device (/dev/input/event5): Failed to open device /dev/input/event5 (13)
> 
> 
> Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
> INFO: Failed to open device (/dev/input/event6): Failed to open device /dev/input/event6 (13)
> 
> 
> Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
> INFO: Failed to open device (/dev/input/event7): Failed to open device /dev/input/event7 (13)
> 
> 
> Jul 15, 2024 5:41:55 AM net.java.games.input.ControllerEnvironment log
> INFO: Linux plugin claims to have found 0 controllers
> 
> 
> Starting up SoundSystem...
> Initializing LWJGL OpenAL
>     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
> OpenAL initialized.
> 
> Failed to add READ_ME_I_AM_VERY_IMPORTANT
> Failed to add pack.mcmeta
> java.io.FileNotFoundException: http://s3.amazonaws.com/MinecraftResources/
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2018)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1611)
> 	at java.base/java.net.URL.openStream(URL.java:1161)
> 	at cz.run(SourceFile:28)
> Connecting to 2beta2t.net, 25565
> Stopping!
> 
> SoundSystem shutting down...
>     Author: Paul Lamb, www.paulscode.com
> 
> Exception in thread "Minecraft main thread" org.lwjgl.LWJGLException: X Error - disp: 0x7931d8043840 serial: 8434 error: GLXBadWindow request_code: 152 minor_code: 32
> 	at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
> 	at org.lwjgl.opengl.LinuxDisplay.nDestroyWindow(Native Method)
> 	at org.lwjgl.opengl.LinuxDisplay.destroyWindow(LinuxDisplay.java:592)
> 	at org.lwjgl.opengl.Display.destroyWindow(Display.java:351)
> 	at org.lwjgl.opengl.Display.access$400(Display.java:65)
> 	at org.lwjgl.opengl.Display$5.destroy(Display.java:835)
> 	at org.lwjgl.opengl.Display.destroy(Display.java:1095)
> 	at net.minecraft.client.Minecraft.d(SourceFile:588)
> 	at net.minecraft.client.Minecraft.run(SourceFile:848)
> 	at java.base/java.lang.Thread.run(Thread.java:840)
> Process exited with exit code 0 (0x0).
> Please note that usually neither the exit code, nor its description are enough to diagnose issues!
> Always upload the entire log and not just the exit code.
> Clipboard copy at: 15 Jul 2024 05:43:44 +0000
> ```

its been 2 years
